# Checks, without building or running anything, that every request in tests/REQUIREMENTS.md
# has tests: each ID must be tagged ([REQ-xx]) on at least one test scenario, and every tag
# must name a request that exists. Also checks the ways to run the tests are there.
#   cmake -DROOT=<FeedView folder> -P tests/requirements_coverage.cmake
# Prints "RESULT PASS|FAIL|SKIP ..." lines like the other tests (see tests/check.h).

if(NOT ROOT)
  get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
set(failed 0)
macro(result status text)
  message(NOTICE "RESULT ${status} ${text}")
  if("${status}" STREQUAL "FAIL")
    set(failed 1)
  endif()
endmacro()

# ---- The requests
file(STRINGS "${ROOT}/tests/REQUIREMENTS.md" rows REGEX "^\\| REQ-[0-9]+ \\|")
set(ids "")
foreach(row IN LISTS rows)
  string(REGEX MATCH "REQ-[0-9]+" id "${row}")
  list(APPEND ids ${id})
endforeach()
list(LENGTH ids count)
if(count EQUAL 0)
  result(FAIL "[REQ-11][REQ-19] tests/REQUIREMENTS.md lists the requests")
  message(FATAL_ERROR "No requests found in tests/REQUIREMENTS.md")
endif()

# ---- The tests and their tags
file(GLOB sources
  "${ROOT}/tests/*.cpp" "${ROOT}/tests/*.cmake" "${ROOT}/tests/*.ps1" "${ROOT}/tests/web/*.mjs" "${ROOT}/companion/feedview/test/*.js")
set(all "")
foreach(f IN LISTS sources)
  file(READ "${f}" text)
  string(APPEND all "${text}\n")
endforeach()

set(missing "")
foreach(id IN LISTS ids)
  string(REGEX MATCHALL "\\[${id}\\]" hits "${all}")
  list(LENGTH hits n)
  # A missing test fails the request; having tests isn't evidence it works, so a passing
  # line isn't tagged (only the tests themselves can make a request pass).
  if(n EQUAL 0)
    list(APPEND missing ${id})
    result(FAIL "[${id}] coverage: no test scenario checks this request")
  else()
    result(PASS "coverage: ${id} has ${n} tagged test scenarios")
  endif()
endforeach()

string(REGEX MATCHALL "\\[REQ-[0-9]+\\]" tags "${all}")
list(REMOVE_DUPLICATES tags)
set(unknown "")
foreach(t IN LISTS tags)
  string(REGEX REPLACE "[][]" "" t "${t}")
  if(NOT t IN_LIST ids)
    list(APPEND unknown ${t})
  endif()
endforeach()
if(unknown)
  result(FAIL "[REQ-19] every tag in the tests names a request in tests/REQUIREMENTS.md (unknown: ${unknown})")
else()
  result(PASS "[REQ-19] every tag in the tests names a request in tests/REQUIREMENTS.md")
endif()
if(missing)
  result(FAIL "[REQ-11][REQ-19] every request (${count}) has tests (missing: ${missing})")
else()
  result(PASS "[REQ-11][REQ-19] every request (${count}) has tests")
endif()

# ---- Claude runs them after every change
set(claude_md "${ROOT}/CLAUDE.md")
if(EXISTS "${claude_md}")
  file(READ "${claude_md}" text)
  if(text MATCHES "run-tests" AND text MATCHES "REQUIREMENTS.md")
    result(PASS "[REQ-11][REQ-19] CLAUDE.md tells every Claude session to keep the tests passing and to add tests for new requests")
  else()
    result(FAIL "[REQ-11][REQ-19] CLAUDE.md tells every Claude session to keep the tests passing and to add tests for new requests")
  endif()
else()
  result(FAIL "[REQ-11][REQ-19] CLAUDE.md is there")
endif()
set(hook_settings "${ROOT}/.claude/settings.local.json")
if(EXISTS "${hook_settings}")
  file(READ "${hook_settings}" text)
  if(text MATCHES "run-tests-if-changed" AND EXISTS "${ROOT}/.claude/hooks/run-tests-if-changed.ps1")
    file(READ "${ROOT}/.claude/hooks/run-tests-if-changed.ps1" hook)
    if(hook MATCHES "scripts\\\\run-tests.ps1" AND hook MATCHES "exit 2")
      result(PASS "[REQ-11][REQ-19] the Claude Code hook runs all tests after Claude's changes and keeps Claude working until they pass")
    else()
      result(FAIL "[REQ-11][REQ-19] the Claude Code hook runs all tests after Claude's changes and keeps Claude working until they pass")
    endif()
  else()
    result(FAIL "[REQ-11][REQ-19] the Claude Code hook (.claude/settings.local.json) runs the tests")
  endif()
else()
  # Another checkout (e.g. CI) has no personal Claude Code settings.
  message(NOTICE "- [REQ-11][REQ-19] the Claude Code hook in .claude/settings.local.json")
  message(NOTICE "  SKIPPED: no .claude/settings.local.json in this checkout")
  message(NOTICE "RESULT SKIP [REQ-11][REQ-19] the Claude Code hook in .claude/settings.local.json")
endif()

# ---- You can run them
set(ok 1)
foreach(f run-tests.cmd scripts/run-tests.ps1 scripts/run-tests.sh scripts/requirements-report.mjs tests/REQUIREMENTS.md)
  if(NOT EXISTS "${ROOT}/${f}")
    set(ok 0)
    message(NOTICE "  missing: ${f}")
  endif()
endforeach()
file(READ "${ROOT}/README.md" readme)
if(NOT readme MATCHES "run-tests.cmd")
  set(ok 0)
  message(NOTICE "  README.md doesn't say how to run the tests (run-tests.cmd)")
endif()
if(ok)
  result(PASS "[REQ-20] run-tests.cmd, the run-tests scripts and the request report are there, and the README explains them")
else()
  result(FAIL "[REQ-20] run-tests.cmd, the run-tests scripts and the request report are there, and the README explains them")
endif()

if(failed)
  message(FATAL_ERROR "Some requests aren't covered by tests (see above)")
endif()
